project:
  type: website
  output-dir: docs
  
website:
  title: "Flavio Mercati"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects
      - href: about.qmd
        text: About

format:
  html:
    theme: litera
    mainfont: "Georgia"
    toc: true