project:
  type: website
  output-dir: docs
  
website:
  title: "Flavio Mercati"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects
      - href: about.qmd
        text: About

format:
  html:
    respect-user-color-scheme: true
    theme:
      dark: [darkly, styles.css]
      light: [simplex, styles.css]
    mainfont: "Georgia"
    toc: true
